### PR TITLE
Create strings.xml for Farsi/Persian

### PR DESCRIPTION
**Pull request by yamin8000**
#120

### CODE REVIEW

**Review by waseefakhtar — COMMENTED** [review]
Looks good @yamin8000! I just notice some phrases are still in English and not translated. Are you going to translate them too? :)

**Comment by yamin8000** [comment]
> Looks good @yamin8000! I just notice some phrases are still in English and not translated. Are you going to translate them too? :)

I edited using my browser so editing parametric ones was a little difficult especially since Farsi is right to left I feared I may mess them up so I just left them for now to edit them later using a proper editor or even build it using AS to test it.

**Comment by yamin8000** [comment]
> Looks good @yamin8000! I just notice some phrases are still in English and not translated. Are you going to translate them too? :)

I fixed the remaining ones.

**Review by waseefakhtar — APPROVED** [review]
Looks great now @yamin8000! 🚀 Thanks for your contribution! :)

**Pull request merged**
