### PR TITLE
Migrate all Gradle files from Groovy to Kotlin

### LINKED ISSUE #121: Migrate all Gradle files from Groovy to Kotlin and enhance the existing ones.
Hi @waseefakhtar , 
 
I've observed that the Module-level Gradle file has already been migrated from Groovy to Kotlin. To maintain consistency, it would be beneficial to migrate the Project-level and Settings Gradle files from Groovy to Kotlin as well.

Furthermore, we can further enhance the Module-level Gradle file by moving certain elements to the libs.version.toml file. This includes:
-  minSdk
-  targetSdk
-  top-level plugins

This approach would improve the overall organization and readability of the Gradle configuration.

Please let me know if you have any questions or concerns regarding this proposal.

### PR DESCRIPTION
**Pull request by ankur141295**
This pull request contains the following changes:

-  Gradle files migrated from Groovy to Kotlin.
-  BuildScript has been removed in favor of Plugins from the Top-Level Gradle File. [See this](https://developer.android.com/build/migrate-to-kotlin-dsl#migrate-buildscript)
-  The app-level Gradle file's plugins block now gets plugin information from a .toml file. Additionally, the compile-sdk, target-sdk, min-sdk, version-code, and version-name data also come from the .toml file.

This change closes #121 

@waseefakhtar Please review the changes and let me know if you have any questions.

### CODE REVIEW

**Review by waseefakhtar — COMMENTED** [review]
This looks great! 👏  

Just one question: Are you sure compile-sdk, target-sdk, min-sdk, version-code, and version-name is retrieved from the .toml file? .toml mentions they're not used anywhere and cmd-clicking on `libs.versions.min.sdk.version.get().toInt()` shows another declaration.

**Comment by ankur141295** [comment]
> This looks great! 👏
> 
> Just one question: Are you sure compile-sdk, target-sdk, min-sdk, version-code, and version-name is retrieved from the .toml file? .toml mentions they're not used anywhere and cmd-clicking on `libs.versions.min.sdk.version.get().toInt()` shows another declaration.

I'm not sure why the usage of some properties isn't displayed in the .toml file. However, if you command-click to open the generated file, you can still see that the declared property is being referenced. For example
Screenshot 2023-12-24 at 1 07 38 PM

Additionally, the Kotlin Compiler Version is also sourced from the .toml file, but it's marked as unused there. However, this code is preexisting and functioning properly.

**Comment by waseefakhtar** [comment]
> > This looks great! 👏
> > Just one question: Are you sure compile-sdk, target-sdk, min-sdk, version-code, and version-name is retrieved from the .toml file? .toml mentions they're not used anywhere and cmd-clicking on `libs.versions.min.sdk.version.get().toInt()` shows another declaration.
> 
> I'm not sure why the usage of some properties isn't displayed in the .toml file. However, if you command-click to open the generated file, you can still see that the declared property is being referenced. For example Screenshot 2023-12-24 at 1 07 38 PM
> 
> Additionally, the Kotlin Compiler Version is also sourced from the .toml file, but it's marked as unused there. However, this code is preexisting and functioning properly.

Okay that makes sense! 👌

**Review by waseefakhtar — APPROVED** [review]
Thank you for your contribution @ankur141295! ✨

**Pull request merged**
